import type { PetSitter, Pet, Booking, Service, User, Review, Availability } from "./types"

export const mockReviews: Review[] = [
  {
    id: "review_001",
    bookingId: "booking_001",
    reviewerId: "user_001",
    reviewerName: "Rajesh Gupta",
    reviewerImage: "/placeholder.svg?height=40&width=40",
    sitterId: "sitter_001",
    rating: 5,
    comment:
      "Priya was absolutely amazing with Bruno! She sent regular updates and photos throughout the day. Bruno came home tired and happy after his walk in Cubbon Park. Highly recommend!",
    serviceType: "dog-walking",
    petName: "Bruno",
    createdAt: "2024-01-10T16:00:00Z",
    helpful: 12,
    response: {
      message:
        "Thank you so much Rajesh! Bruno is such a sweet boy and it was a pleasure spending time with him. Looking forward to our next walk!",
      createdAt: "2024-01-10T18:30:00Z",
    },
  },
  {
    id: "review_002",
    bookingId: "booking_002",
    reviewerId: "user_002",
    reviewerName: "Sneha Patel",
    reviewerImage: "/placeholder.svg?height=40&width=40",
    sitterId: "sitter_001",
    rating: 5,
    comment:
      "Professional, caring, and reliable. Priya took excellent care of our cat Mittens while we were away. She followed all our instructions perfectly and even sent videos!",
    serviceType: "pet-sitting",
    petName: "Mittens",
    createdAt: "2024-01-05T14:20:00Z",
    helpful: 8,
  },
  {
    id: "review_003",
    bookingId: "booking_003",
    reviewerId: "user_003",
    reviewerName: "Vikram Singh",
    reviewerImage: "/placeholder.svg?height=40&width=40",
    sitterId: "sitter_002",
    rating: 4,
    comment:
      "Arjun did a great job with our energetic puppy Rocky. He's clearly experienced with dogs and handled Rocky's energy level perfectly during the walk in Lalbagh.",
    serviceType: "dog-walking",
    petName: "Rocky",
    createdAt: "2024-01-08T11:15:00Z",
    helpful: 5,
  },
  {
    id: "review_004",
    bookingId: "booking_004",
    reviewerId: "user_004",
    reviewerName: "Meera Krishnan",
    reviewerImage: "/placeholder.svg?height=40&width=40",
    sitterId: "sitter_003",
    rating: 5,
    comment:
      "Kavya is fantastic! She has such a gentle way with senior pets. Our 12-year-old cat Whiskers was completely comfortable with her. Her experience really shows.",
    serviceType: "pet-sitting",
    petName: "Whiskers",
    createdAt: "2024-01-03T09:45:00Z",
    helpful: 15,
  },
]

export const mockSitters: PetSitter[] = [
  {
    id: "sitter_001",
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya.sharma@email.com",
    phone: "+91-98765-43210",
    profileImage: "/placeholder.svg?height=120&width=120",
    rating: 4.9,
    reviewCount: 127,
    experienceYears: 5,
    hourlyRate: 400,
    bio: "I'm a passionate pet lover with over 5 years of experience caring for dogs and cats in Bengaluru. I treat every pet as if they were my own and provide regular updates throughout the day. I understand that leaving your furry family member with someone else can be stressful, so I make sure to keep you informed and your pet happy and comfortable.",
    specialties: ["Dogs", "Cats", "Small Animals", "Senior Pets"],
    languages: ["English", "Hindi", "Kannada"],
    education: ["Bachelor's in Veterinary Science - UAS Bengaluru"],
    certifications: ["Pet First Aid Certified", "Dog Training Certificate"],
    availability: {
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: false,
    },
    services: ["dog-walking", "pet-sitting", "overnight-care"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      zipCode: "560001",
      coordinates: { lat: 12.9716, lng: 77.5946 },
      radius: 15,
    },
    verified: true,
    backgroundCheck: true,
    insurance: true,
    emergencyTrained: true,
    petFirstAid: true,
    responseTime: "within 1 hour",
    cancellationPolicy: "Free cancellation up to 24 hours before service",
    pricing: {
      baseRate: 400,
      holidayRate: 550,
      lastMinuteRate: 480,
    },
    gallery: [
      "/placeholder.svg?height=200&width=300",
      "/placeholder.svg?height=200&width=300",
      "/placeholder.svg?height=200&width=300",
    ],
    joinedDate: "2023-01-15T10:00:00Z",
    lastActive: "2024-01-15T08:30:00Z",
    createdAt: "2023-01-15T10:00:00Z",
    updatedAt: "2024-01-10T15:30:00Z",
  },
  {
    id: "sitter_002",
    firstName: "Arjun",
    lastName: "Reddy",
    email: "arjun.reddy@email.com",
    phone: "+91-98765-43211",
    profileImage: "/placeholder.svg?height=120&width=120",
    rating: 4.8,
    reviewCount: 89,
    experienceYears: 3,
    hourlyRate: 450,
    bio: "Former veterinary assistant with extensive experience with large breed dogs in Bengaluru. I love active dogs and enjoy long walks in Cubbon Park and Lalbagh. I have a special interest in dog behavior and training, and I'm great at handling anxious or energetic pets.",
    specialties: ["Dogs", "Large Breeds", "Puppies", "Behavioral Training"],
    languages: ["English", "Telugu", "Kannada"],
    education: ["Veterinary Assistant Certificate - Bangalore Veterinary College"],
    certifications: ["Pet CPR Certified", "Canine Behavior Specialist"],
    availability: {
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: true,
    },
    services: ["dog-walking", "pet-sitting", "grooming"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      zipCode: "560002",
      coordinates: { lat: 12.9352, lng: 77.6245 },
      radius: 12,
    },
    verified: true,
    backgroundCheck: true,
    insurance: true,
    emergencyTrained: false,
    petFirstAid: true,
    responseTime: "within 2 hours",
    cancellationPolicy: "Free cancellation up to 12 hours before service",
    pricing: {
      baseRate: 450,
      holidayRate: 600,
      lastMinuteRate: 520,
    },
    gallery: ["/placeholder.svg?height=200&width=300", "/placeholder.svg?height=200&width=300"],
    joinedDate: "2023-03-20T14:00:00Z",
    lastActive: "2024-01-14T19:45:00Z",
    createdAt: "2023-03-20T14:00:00Z",
    updatedAt: "2024-01-08T09:15:00Z",
  },
  {
    id: "sitter_003",
    firstName: "Kavya",
    lastName: "Nair",
    email: "kavya.nair@email.com",
    phone: "+91-98765-43212",
    profileImage: "/placeholder.svg?height=120&width=120",
    rating: 5.0,
    reviewCount: 156,
    experienceYears: 7,
    hourlyRate: 500,
    bio: "Certified animal behaviorist specializing in cats and exotic pets in Bengaluru. I have experience with special needs animals and medication administration. I'm patient, gentle, and understand that every pet has unique needs and personality. I serve areas like Koramangala, Indiranagar, and HSR Layout.",
    specialties: ["Cats", "Exotic Pets", "Senior Pets", "Special Needs", "Medication Administration"],
    languages: ["English", "Malayalam", "Kannada"],
    education: ["Master's in Animal Behavior - UAS Bengaluru", "Veterinary Technician Degree"],
    certifications: ["Animal Behaviorist Certification", "Exotic Pet Care Specialist"],
    availability: {
      monday: true,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: true,
      saturday: false,
      sunday: true,
    },
    services: ["pet-sitting", "overnight-care", "vet-visit"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      zipCode: "560034",
      coordinates: { lat: 12.9279, lng: 77.6271 },
      radius: 18,
    },
    verified: true,
    backgroundCheck: true,
    insurance: true,
    emergencyTrained: true,
    petFirstAid: true,
    responseTime: "within 30 minutes",
    cancellationPolicy: "Free cancellation up to 48 hours before service",
    pricing: {
      baseRate: 500,
      holidayRate: 650,
      lastMinuteRate: 580,
    },
    gallery: [
      "/placeholder.svg?height=200&width=300",
      "/placeholder.svg?height=200&width=300",
      "/placeholder.svg?height=200&width=300",
      "/placeholder.svg?height=200&width=300",
    ],
    joinedDate: "2022-11-10T08:00:00Z",
    lastActive: "2024-01-15T12:20:00Z",
    createdAt: "2022-11-10T08:00:00Z",
    updatedAt: "2024-01-12T11:45:00Z",
  },
  {
    id: "sitter_004",
    firstName: "Rohit",
    lastName: "Kumar",
    email: "rohit.kumar@email.com",
    phone: "+91-98765-43213",
    profileImage: "/placeholder.svg?height=120&width=120",
    rating: 4.7,
    reviewCount: 73,
    experienceYears: 2,
    hourlyRate: 350,
    bio: "Energetic college student who loves spending time with pets in Bengaluru. Great with playful dogs and cats who need lots of attention and exercise. I'm available for flexible scheduling and love building relationships with both pets and their families. I cover areas like Whitefield, Marathahalli, and Electronic City.",
    specialties: ["Young Dogs", "Active Pets", "Playtime", "Exercise"],
    languages: ["English", "Hindi", "Kannada"],
    education: ["Currently studying Veterinary Medicine - Rajiv Gandhi University"],
    certifications: ["Pet First Aid Certified"],
    availability: {
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: true,
    },
    services: ["dog-walking", "pet-sitting", "playtime"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      zipCode: "560066",
      coordinates: { lat: 12.9698, lng: 77.75 },
      radius: 10,
    },
    verified: true,
    backgroundCheck: false,
    insurance: true,
    emergencyTrained: false,
    petFirstAid: true,
    responseTime: "within 3 hours",
    cancellationPolicy: "Free cancellation up to 6 hours before service",
    pricing: {
      baseRate: 350,
      holidayRate: 420,
      lastMinuteRate: 400,
    },
    gallery: ["/placeholder.svg?height=200&width=300"],
    joinedDate: "2023-09-01T16:00:00Z",
    lastActive: "2024-01-15T14:10:00Z",
    createdAt: "2023-09-01T16:00:00Z",
    updatedAt: "2024-01-13T20:30:00Z",
  },
  {
    id: "sitter_005",
    firstName: "Ananya",
    lastName: "Iyer",
    email: "ananya.iyer@email.com",
    phone: "+91-98765-43214",
    profileImage: "/placeholder.svg?height=120&width=120",
    rating: 4.6,
    reviewCount: 45,
    experienceYears: 4,
    hourlyRate: 420,
    bio: "Professional pet groomer and sitter with 4 years of experience in Bengaluru. I specialize in grooming services and have my own mobile grooming setup. I'm passionate about pet hygiene and health, and I love making pets look and feel their best.",
    specialties: ["Grooming", "Small Dogs", "Cats", "Hygiene Care"],
    languages: ["English", "Tamil", "Kannada"],
    education: ["Professional Pet Grooming Certificate"],
    certifications: ["Certified Pet Groomer", "Pet Hygiene Specialist"],
    availability: {
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: true,
      sunday: false,
    },
    services: ["grooming", "pet-sitting", "overnight-care"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      zipCode: "560017",
      coordinates: { lat: 13.0067, lng: 77.5818 },
      radius: 14,
    },
    verified: true,
    backgroundCheck: true,
    insurance: true,
    emergencyTrained: false,
    petFirstAid: true,
    responseTime: "within 4 hours",
    cancellationPolicy: "Free cancellation up to 24 hours before service",
    pricing: {
      baseRate: 420,
      holidayRate: 520,
      lastMinuteRate: 480,
    },
    gallery: ["/placeholder.svg?height=200&width=300", "/placeholder.svg?height=200&width=300"],
    joinedDate: "2023-05-15T10:00:00Z",
    lastActive: "2024-01-14T16:30:00Z",
    createdAt: "2023-05-15T10:00:00Z",
    updatedAt: "2024-01-11T14:20:00Z",
  },
]

// Mock availability data
export const mockAvailability: Record<string, Availability[]> = {
  sitter_001: [
    {
      date: "2024-01-16",
      timeSlots: [
        { startTime: "08:00", endTime: "10:00", available: true, price: 400 },
        { startTime: "10:00", endTime: "12:00", available: true, price: 400 },
        { startTime: "14:00", endTime: "16:00", available: false },
        { startTime: "16:00", endTime: "18:00", available: true, price: 400 },
      ],
    },
    {
      date: "2024-01-17",
      timeSlots: [
        { startTime: "09:00", endTime: "11:00", available: true, price: 400 },
        { startTime: "15:00", endTime: "17:00", available: true, price: 400 },
      ],
    },
  ],
  sitter_002: [
    {
      date: "2024-01-16",
      timeSlots: [
        { startTime: "07:00", endTime: "09:00", available: true, price: 450 },
        { startTime: "12:00", endTime: "14:00", available: false },
        { startTime: "17:00", endTime: "19:00", available: true, price: 450 },
      ],
    },
  ],
  sitter_003: [
    {
      date: "2024-01-16",
      timeSlots: [
        { startTime: "10:00", endTime: "12:00", available: true, price: 500 },
        { startTime: "14:00", endTime: "16:00", available: true, price: 500 },
        { startTime: "18:00", endTime: "20:00", available: false },
      ],
    },
  ],
  sitter_004: [
    {
      date: "2024-01-16",
      timeSlots: [
        { startTime: "08:00", endTime: "10:00", available: true, price: 350 },
        { startTime: "10:00", endTime: "12:00", available: true, price: 350 },
        { startTime: "14:00", endTime: "16:00", available: true, price: 350 },
        { startTime: "16:00", endTime: "18:00", available: true, price: 350 },
      ],
    },
  ],
  sitter_005: [
    {
      date: "2024-01-16",
      timeSlots: [
        { startTime: "09:00", endTime: "11:00", available: true, price: 420 },
        { startTime: "11:00", endTime: "13:00", available: false },
        { startTime: "15:00", endTime: "17:00", available: true, price: 420 },
      ],
    },
  ],
}

// Keep existing mockPets, mockServices, mockBookings, mockUser...
export const mockPets: Pet[] = [
  {
    id: "pet_001",
    name: "Max",
    type: "dog",
    breed: "Golden Retriever",
    age: 3,
    weight: 65,
    gender: "male",
    spayed: false,
    vaccinated: true,
    microchipped: true,
    specialNeeds: ["Needs water breaks during walks"],
    medications: [],
    allergies: ["Chicken"],
    emergencyContact: {
      name: "John Smith",
      phone: "+1-555-0100",
      relationship: "Owner",
    },
    vetInfo: {
      name: "City Veterinary Clinic",
      phone: "+1-555-0200",
      address: "123 Main St, New York, NY 10001",
    },
    profileImage: "/placeholder.svg?height=120&width=120",
    ownerId: "user_001",
    createdAt: "2023-06-15T12:00:00Z",
    updatedAt: "2024-01-05T16:20:00Z",
  },
  {
    id: "pet_002",
    name: "Luna",
    type: "cat",
    breed: "Persian",
    age: 2,
    weight: 8,
    gender: "female",
    spayed: true,
    vaccinated: true,
    microchipped: true,
    specialNeeds: ["Shy, needs quiet environment"],
    medications: [],
    allergies: [],
    emergencyContact: {
      name: "John Smith",
      phone: "+1-555-0100",
      relationship: "Owner",
    },
    vetInfo: {
      name: "City Veterinary Clinic",
      phone: "+1-555-0200",
      address: "123 Main St, New York, NY 10001",
    },
    profileImage: "/placeholder.svg?height=120&width=120",
    ownerId: "user_001",
    createdAt: "2023-08-20T10:30:00Z",
    updatedAt: "2024-01-03T14:15:00Z",
  },
]

export const mockServices: Service[] = [
  {
    id: "dog-walking",
    name: "Dog Walking",
    description: "Professional dog walking service for 30-60 minutes",
    basePrice: 300,
    duration: 45,
    category: "exercise",
    icon: "🐕",
    active: true,
  },
  {
    id: "pet-sitting",
    name: "Pet Sitting",
    description: "In-home pet sitting for 4-8 hours",
    basePrice: 800,
    duration: 360,
    category: "care",
    icon: "🏠",
    active: true,
  },
  {
    id: "overnight-care",
    name: "Overnight Care",
    description: "Overnight pet care in your home",
    basePrice: 1500,
    duration: 720,
    category: "care",
    icon: "🌙",
    active: true,
  },
  {
    id: "pet-boarding",
    name: "Pet Boarding",
    description: "Pet stays at sitter's home for 24 hours",
    basePrice: 1200,
    duration: 1440,
    category: "boarding",
    icon: "🏨",
    active: true,
  },
  {
    id: "grooming",
    name: "Pet Grooming",
    description: "Professional grooming service",
    basePrice: 1000,
    duration: 150,
    category: "grooming",
    icon: "✂️",
    active: true,
  },
  {
    id: "vet-visit",
    name: "Vet Visit Companion",
    description: "Accompany your pet to vet appointments",
    basePrice: 600,
    duration: 180,
    category: "health",
    icon: "🏥",
    active: true,
  },
]

export const mockBookings: Booking[] = [
  {
    id: "booking_001",
    petId: "pet_001",
    sitterId: "sitter_001",
    ownerId: "user_001",
    serviceType: "dog-walking",
    status: "confirmed",
    startDateTime: "2024-01-15T09:00:00Z",
    endDateTime: "2024-01-15T10:00:00Z",
    totalAmount: 25,
    paymentStatus: "paid",
    specialInstructions: "Max loves to play fetch and needs water breaks",
    location: {
      address: "Central Park West",
      city: "New York",
      state: "NY",
      zipCode: "10024",
    },
    additionalServices: ["photos"],
    createdAt: "2024-01-10T14:30:00Z",
    updatedAt: "2024-01-10T14:30:00Z",
  },
  {
    id: "booking_002",
    petId: "pet_002",
    sitterId: "sitter_002",
    ownerId: "user_001",
    serviceType: "pet-sitting",
    status: "ongoing",
    startDateTime: "2024-01-12T18:00:00Z",
    endDateTime: "2024-01-14T10:00:00Z",
    totalAmount: 120,
    paymentStatus: "paid",
    specialInstructions: "Shy cat, needs quiet environment",
    location: {
      address: "456 Downtown Ave",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    additionalServices: ["feeding", "medication"],
    createdAt: "2024-01-08T16:45:00Z",
    updatedAt: "2024-01-12T18:00:00Z",
  },
  {
    id: "booking_003",
    petId: "pet_001",
    sitterId: "sitter_003",
    ownerId: "user_001",
    serviceType: "overnight-care",
    status: "completed",
    startDateTime: "2024-01-08T19:00:00Z",
    endDateTime: "2024-01-10T09:00:00Z",
    totalAmount: 180,
    paymentStatus: "paid",
    specialInstructions: "",
    location: {
      address: "789 Suburban Lane",
      city: "New York",
      state: "NY",
      zipCode: "10003",
    },
    additionalServices: ["playtime"],
    createdAt: "2024-01-05T12:20:00Z",
    updatedAt: "2024-01-10T09:30:00Z",
  },
]

export const mockUser: User = {
  id: "user_001",
  firstName: "Rajesh",
  lastName: "Gupta",
  email: "rajesh.gupta@email.com",
  phone: "+91-98765-43200",
  profileImage: "/placeholder.svg?height=120&width=120",
  address: {
    street: "123 MG Road",
    city: "Bengaluru",
    state: "Karnataka",
    zipCode: "560001",
  },
  pets: mockPets,
  createdAt: "2023-05-01T10:00:00Z",
  updatedAt: "2024-01-01T12:00:00Z",
}
